"""
Legal analysis and Q&A service.
"""

from backend.rag.retriever import retrieve_context
from backend.utils.gemini import call_with_fallback
from backend.prompts.rag import RAG_ANSWER_PROMPT, IPC_ANALYSIS_PROMPT

__all__ = ["LegalService"]


class LegalService:
    """Service for legal analysis and document Q&A."""

    def __init__(self) -> None:
        """Initialize the LegalService."""
        pass

    def analyze_case(self, case_description: str) -> str:
        """
        Analyze a case description and extract IPC sections using Ollama.
        """
        from langchain_ollama import ChatOllama
        from backend.schemas.intents import CaseAnalysisResult
        import os
        
        OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
        OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2")
        
        llm = ChatOllama(model=OLLAMA_MODEL, base_url=OLLAMA_BASE_URL, temperature=0).with_structured_output(CaseAnalysisResult)
        
        try:
            result = llm.invoke(f"{IPC_ANALYSIS_PROMPT}\n\nCase Description: {case_description}")
            return result.model_dump_json(indent=2)
        except Exception as e:
            return f"{{\"summary\": \"Error\", \"applicable_ipc_sections\": [], \"analysis\": \"Failed to analyze: {str(e)}\"}}"


    def answer_document_query(self, query: str, collection_name: str) -> str:
        """
        Answer a query based on document context using RAG.
        
        Args:
            query (str): The user's query.
            collection_name (str): The ChromaDB collection name.
            
        Returns:
            str: Answer generated by the LLM.
        """
        context = retrieve_context(query, collection_name)
        prompt = RAG_ANSWER_PROMPT.format(context=context, query=query)
        
        messages = [
            {"role": "system", "content": prompt},
            {"role": "user", "content": query}
        ]
        return call_with_fallback(messages=messages)
