"""
Legal analysis and Q&A service.
"""

from backend.rag.retriever import retrieve_context
from backend.utils.gemini import call_with_fallback
from backend.prompts.rag import RAG_ANSWER_PROMPT, IPC_ANALYSIS_PROMPT

__all__ = ["LegalService"]


class LegalService:
    """Service for legal analysis and document Q&A."""

    def __init__(self) -> None:
        """Initialize the LegalService."""
        pass

    def analyze_case(self, case_description: str) -> str:
        """
        Analyze a case description and extract IPC sections using Gemini.
        
        Args:
            case_description (str): Description of the case.
            
        Returns:
            str: Analysis containing IPC sections.
        """
        messages = [
            {"role": "system", "content": IPC_ANALYSIS_PROMPT},
            {"role": "user", "content": case_description}
        ]
        return call_with_fallback(messages=messages)

    def answer_document_query(self, query: str, collection_name: str) -> str:
        """
        Answer a query based on document context using RAG.
        
        Args:
            query (str): The user's query.
            collection_name (str): The ChromaDB collection name.
            
        Returns:
            str: Answer generated by the LLM.
        """
        context = retrieve_context(query, collection_name)
        prompt = RAG_ANSWER_PROMPT.format(context=context, query=query)
        
        messages = [
            {"role": "system", "content": prompt},
            {"role": "user", "content": query}
        ]
        return call_with_fallback(messages=messages)
