"""add_similar_cases_table

Revision ID: 9a01f8fb7bf7
Revises: c4246997da0f
Create Date: 2026-08-06 22:49:39.189151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a01f8fb7bf7'
down_revision: Union[str, Sequence[str], None] = 'c4246997da0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_name', sa.String(length=500), nullable=False),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('decision_date', sa.String(length=50), nullable=True),
    sa.Column('citation', sa.String(length=255), nullable=True),
    sa.Column('case_type', sa.String(length=100), nullable=True),
    sa.Column('legal_domain', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('chroma_doc_id', sa.String(length=255), nullable=True),
    sa.Column('ipc_sections', sa.JSON(), nullable=False),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_doc_id')
    )
    op.create_index(op.f('ix_similar_cases_case_name'), 'similar_cases', ['case_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similar_cases_case_name'), table_name='similar_cases')
    op.drop_table('similar_cases')
    # ### end Alembic commands ###
